# TOML format, v0.5.0.

modLoader="javafml"
loaderVersion="${loader_version}"
license="The Unlicense"
issueTrackerURL="https://github.com/AustinMReppert/graph-io/issues"

[[mods]]

modId="graphio"
version="${version}"
displayName="Graph IO"

# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/AustinMReppert/graph-io/" #optional
logoFile="logo.png" #optional
credits="This mod was inspired by XNet."
authors="Austin M. Reppert"
description='''
This is a simple mod meant for transport items, energy, fluids, etc. in a performant manner.
'''